logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

server.port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          client-id:
            client-id: 0oaj42d3hpR3EVrtK0h7
            provider: okta
            scopes: email,openid,profile
            client-authentication-method: none
        provider:
          okta:
            issuer-uri: https://dev-334545.oktapreview.com/oauth2/default

resource-uri: https://dev-334545.oktapreview.com/oauth2/default/v1/userinfo
